web/router.ex
defmodule Medium.Router do
  use Medium.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Medium.Auth, repo: Medium.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Medium do
    pipe_through :browser # Use the default browser stack

    get "/signup", PageController, :signup
    get "/login", PageController, :login
    resources "/registrations", RegistrationController, only: [:create]
    resources "/sessions", SessionController, only: [:create, :delete]

    get "/", PostController, :index
    resources "/posts", PostController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Medium do
  #   pipe_through :api
  # end
end

lib/medium/endpoint.ex
defmodule Medium.Endpoint do
  use Phoenix.Endpoint, otp_app: :medium

  socket "/socket", Medium.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :medium, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_medium_key",
    signing_salt: "wFw/ru0v"

  plug Medium.Router
end

lib/medium/repo.ex
defmodule Medium.Repo do
  use Ecto.Repo, otp_app: :medium
end

web/models/post.ex
defmodule Medium.Post do
  use Medium.Web, :model

  schema "posts" do
    field :title, :string
    field :body, :string
    belongs_to :user, Medium.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :body])
    |> validate_required([:title, :body])
  end
end

web/models/user.ex
defmodule Medium.User do
  use Medium.Web, :model
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]
  alias Ecto.Changeset

  schema "users" do
    field :name, :string
    field :username, :string
    field :password_hash, :string
    field :password, :string, virtual: true
    has_many :posts, Medium.Post

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :username])
    |> validate_required([:name, :username])
  end

  def registration_changeset(struct, params) do
    struct
    |> changeset(params)
    |> cast(params, ~w(password))
    |> validate_length(:password, min: 6, max: 100)
    |> encrypt_password()
  end

  defp encrypt_password(changeset) do
    case changeset do
      %Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Medium.PageController do
  use Medium.Web, :controller

  def signup(conn, _params) do
    changeset = Medium.User.changeset(%Medium.User{})
    conn
    |> assign(:changeset, changeset)
    |> render("signup.html")
  end

  def login(conn, _params) do
    changeset = Medium.User.changeset(%Medium.User{})
    conn
    |> assign(:changeset, changeset)
    |> render("login.html")
  end
end

web/controllers/post_controller.ex
defmodule Medium.PostController do
  use Medium.Web, :controller
  alias Medium.Post
  import Ecto.Query

  def index(conn, _params) do
    query = from p in Post,
            order_by: [desc: p.inserted_at],
            preload: :user,
            select: p

    posts = Repo.all(query)

    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    conn
    |> put_layout("post.html")
    |> render("new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    changeset = Ecto.build_assoc(conn.assigns.current_user, :posts)
                |> Post.changeset(post_params)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: post_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: post_path(conn, :index))
  end
end

web/controllers/registration_controller.ex
defmodule Medium.RegistrationController do
  use Medium.Web, :controller
  alias Medium.User

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> Medium.Auth.login(user)
        |> redirect(to: "/")
      {:error, changeset} ->
        render(conn, "page/signup.html", changeset: changeset)
    end
  end
end

web/controllers/session_controller.ex
defmodule Medium.SessionController do
  use Medium.Web, :controller
  alias Medium.Auth

  def create(conn, %{"user" => user_params}) do
    %{"username" => username, "password" => password} = user_params
    case Auth.login_by_username_and_password(conn, username, password, repo: Repo) do
      {:ok, conn} ->
        conn
        |> redirect(to: "/")
      {:error, _reason, conn} ->
        conn
        |> render("page/login.html")
    end
  end
end

web/views/error_view.ex
defmodule Medium.ErrorView do
  use Medium.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Medium.LayoutView do
  use Medium.Web, :view
end

web/views/page_view.ex
defmodule Medium.PageView do
  use Medium.Web, :view
end

web/views/post_view.ex
defmodule Medium.PostView do
  use Medium.Web, :view

  def author_name(post) do
    case post.user do
      nil -> "Anonymous"
      user -> user.name
    end
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog</title>

    <!-- Theme CSS -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            Menu <i class="fa fa-bars"></i>
          </button>
          <a class="navbar-brand" href="<%= post_path(@conn, :index) %>">Medium</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a href="<%= post_path(@conn, :index) %>">Home</a>
            </li>
            <li>
              <a href="<%= post_path(@conn, :new) %>">New Post</a>
            </li>
            <%= if @current_user do %>
              <li><a href="#"><%= @current_user.name %></a></li>
              <li><%= link "Sign out", to: "#" %></li>
            <% else %>
              <li>
                <a href="<%= page_path(@conn, :login) %>">Login</a>
              </li>
              <li>
                <a href="<%= page_path(@conn, :signup) %>">Sign Up</a>
              </li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/images/home-bg.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="site-heading">
              <h1>Medium</h1>
              <hr class="small">
              <span class="subheading">A medium clone by Joel G Martinez</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
          </div>
        </div>
      </div>
    </footer>

  </body>

</html>

web/templates/layout/old_app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Medium!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/post.html.eex
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog</title>

    <!-- Theme CSS -->
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>

  <body>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Joel G Martinez 2016</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

web/templates/page/index.html.eex
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
  <div class="post-preview">
    <a href="post.html">
      <h2 class="post-title">
        Man must explore, and this is exploration at its greatest
      </h2>
      <h3 class="post-subtitle">
        Problems look mighty small from 150 miles up
      </h3>
    </a>
    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 24, 2014</p>
  </div>
  <hr>
  <div class="post-preview">
    <a href="post.html">
      <h2 class="post-title">
        I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
      </h2>
    </a>
    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on September 18, 2014</p>
  </div>
  <hr>
  <div class="post-preview">
    <a href="post.html">
      <h2 class="post-title">
        Science has not yet mastered prophecy
      </h2>
      <h3 class="post-subtitle">
        We predict too much for the next year and yet far too little for the next ten.
      </h3>
    </a>
    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</p>
  </div>
  <hr>
  <div class="post-preview">
    <a href="post.html">
      <h2 class="post-title">
        Failure is not an option
      </h2>
      <h3 class="post-subtitle">
        Many say exploration is part of our destiny, but it’s actually our duty to future generations.
      </h3>
    </a>
    <p class="post-meta">Posted by <a href="#">Start Bootstrap</a> on July 8, 2014</p>
  </div>
  <hr>
  <!-- Pager -->
  <ul class="pager">
    <li class="next">
      <a href="#">Older Posts &rarr;</a>
    </li>
  </ul>
</div>

web/templates/page/login.html.eex
<%= form_for @changeset, session_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Login!", class: "btn btn-primary" %>
<% end %>

web/templates/page/signup.html.eex
<%= form_for @changeset, registration_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %>
<% end %>

web/templates/post/edit.html.eex
<h2>Edit post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :update, @post) %>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= text_input f, :title, class: "form-control", placeholder: "Title" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= textarea f, :body, class: "form-control", placeholder: "Enter your post content here..." %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/post/index.html.eex
<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
  <%= for post <- @posts do %>
    <div class="post-preview">
      <a href="<%= post_path(@conn, :show, post) %>">
        <h2 class="post-title">
          <%= post.title %>
        </h2>
        <h3 class="post-subtitle">
          <%= post.body %>
        </h3>
      </a>
      <p class="post-meta">Posted by <a href="#"><%= author_name post %></a> on <%= post.inserted_at %></p>
    </div>
    <hr>
  <% end %>
  <!-- Pager -->
  <ul class="pager">
    <li class="next">
      <a href="#">Older Posts &rarr;</a>
    </li>
  </ul>
</div>

web/templates/post/new.html.eex
<h2>New post</h2>

<%= render "form.html", changeset: @changeset,
                        action: post_path(@conn, :create) %>

<%= link "Back", to: post_path(@conn, :index) %>

web/templates/post/show.html.eex
<h2><%= @post.title %></h2>

<div>
  <%= @post.body %>
</div>
<hr/>